@startuml 1b

note "KORREKTE UML SYNTAX BEIM ABZEICHNEN BEACHTEN!!!" as n2

'' Paragraph 1

note "verbundene Objekte gehören eigentlich\n(sofern möglich) ineinander geschachtelt" as n1

object "Alfred:Benutzer" as b1{
    benutzername = "alfred"
    rolle
}
object "rolle:Administrator" as r1
b1::rolle - r1


object "Ulrich:Benutzer" as b2{
    benutzername = "ulrich"
    rolle
}
object "rolle:Übersetzer" as ü2
b2::rolle - ü2

object "Uwe:Benutzer" as b3{
    benutzername = "uwe"
    rolle
}
object "rolle:Übersetzer" as ü3
b3::rolle - ü3

object "Udo:Benutzer" as b4{
    benutzername = "udo"
    rolle
}
object "rolle:Übersetzer" as ü4
b4::rolle - ü4

object "Urs:Benutzer" as b5{
    benutzername = "urs"
    rolle
}
object "rolle:Übersetzer" as ü5
b5::rolle - ü5

object "Siggi:Benutzer" as b6{
    benutzername = "siggi"
    rolle
}
object "rolle:Sprachprüfer" as s6
b6::rolle - s6

object "Ferdinand:Benutzer" as b7{
    benutzername = "ferdinand"
    rolle
}
object "rolle:Fachprüfer" as f7
b7::rolle - f7

object "Peter:Benutzer" as b8{
    benutzername = "peter"
    rolle
}
object "rolle:ProduktManager" as p8
b8::rolle - p8

'' Paragraph 2

object "Deutschland:Land" as DE{
    bezeichnung = "DE"
}
object "Schweiz:Land" as CH{
    bezeichnung = "CH"
}
object "Frankreich:Land" as FR{
    bezeichnung = "FR"
}
object "Luxemburg:Land" as LU{
    bezeichnung = "LU"
}

'' Paragraph 3

object "Deutsch:Sprache" as de{
    bezeichnung = "de"
}
object "Französisch:Sprache" as fr{
    bezeichnung = "fr"
}
object "Italienisch:Sprache" as it{
    bezeichnung = "it"
}
object "Luxemburgisch:Sprache" as lb{
    bezeichnung = "lu"
}

DE -- de
CH -- fr
CH -- it
CH -- de
LU -- fr
LU -- de
LU -- lb
FR -- fr

ü2 - (DE,de)
ü3 -- (CH,fr)
ü4 - (CH,it)
ü2 -- (CH,de)
ü3 - (LU,fr)
ü2 -- (LU,de)
ü5 - (LU,lb)
ü3 -- (FR,fr)



@enduml