' TIME WASTED: 2h
@startuml

' Für Anleitungen
' Also wie Anleitungen gepflegt werden

' TODO Benutzer dürfen niemals Freigaben erteilen für Übersetzungen,
' TODO die sie selbst hochgeladen haben.


note as n1
    "Eine Fachlich oder Sprachlich zurückgewiesene
    Übersetzung kann in keinerei Hinsicht freigegeben werden"
end note

[*] --> prodExists : produktAnlegen()
state "Produkt existiert" as prodExists{
    [*] --> missing
    state "Anleitung in\nSprache-Land Kombi fehlt" as missing
    missing --> Processing : anleitungHochladen()
    state Processing{
        state "Anleitung hochgeladen" as av
        [*] --> av
        state "sprachlich Freigegeben" as sprachFrei
        state "fachlich Freigegeben" as fachFrei
        state "final" as final
        state "sprachlich zurückgewiesen" as sprachZurück
        state "sprachlich zurückgewiesen" as sprachZurück1
        state "fachlich zurückgewisesn" as fachZurück
        state "fachlich zurückgewisesn" as fachZurück1

        ' TODO übergänge sind noch nicht eindeutig.
        av --> sprachFrei : anleitungFreigeben()
        sprachFrei -> fachZurück : anleitungZurückweisen()
        av --> fachFrei : anleitungFreigeben()
        fachFrei -> sprachZurück : anleitungZurückweisen()
        sprachFrei --> final : anleitungFreigeben()
        fachFrei --> final : anleitungFreigeben()
        av -> fachZurück1 : anleitungZurückweisen()
        av -> sprachZurück1 : anleitungZurückweisen()
        sprachZurück1 --> fachZurück : anleitungZurückweisen()
        fachZurück1 --> sprachZurück : anleitungZurückweisen()

        av <-- final : anleitungHochladen()
    }
    Processing --> missing : übersetzungLöschen()
}
state "Produkt gesperrt" as prodLock{
    state "Anleitung gesperrt" as gesperrt
}
final -> gesperrt : produktSperren()
final <- gesperrt : produktSperreAufheben()
prodExists --> prodLock : produktSperren()
prodExists <-- prodLock : produktSperreAufheben()
prodExists --> [*] : produktLöschen()

@enduml