' Time Wasted 1.5H
@startuml Alle

' ROLLEN
:Benutzer: as user
:ProductManager: as pm
:Administrator: as admin
:FachPrüfer: as fp
:SprachPrüfer: as sp
:Übersetzer: as tr

' User kann Rollen haben
user <|-- pm
user <|-- admin
user <|-- fp
user <|-- sp
user <|-- tr

rectangle ManualMasters{


    ' Admin Rolle
    (spracheAnlegen) as adminSp
    (landAnlegen) as adminLd
    (landSpracheZuordnen) as adminSpLd
    (benutzerPflegen) as adminUser
    (berichtErzeugen) as adminBericht
    (übersetzungLöschen) as adminÜbDel
    (produktLöschen) as adminProdDel
    admin -- adminSp
    admin -- adminLd
    admin -- adminSpLd
    admin -- adminUser
    admin -- adminBericht
    admin -- adminÜbDel
    admin -- adminProdDel
    adminProdDel .> adminÜbDel : <<include>>

    ' Product Manager
    (produktAnlegen) as pmProdCr
    (produktBearbeiten) as pmProdEdit
    (produktSperren) as pmProdLock
    (produktSperreAufheben) as pmProdUnlock
    (fehlendeÜbersetzungenAnzeigen) as pmTrShow
    (freigabestatusAnzeigen) as pmFrei
    pm -- pmProdCr
    pm -- pmProdEdit
    pm -- pmProdLock
    pm -- pmProdUnlock
    pm -- pmTrShow
    pm -- pmFrei

    ' Übersetzer
    (fehlendeÜbersetzungenAnzeigen) as TrShowMissing
    (vorhandeneÜbersetzungenAnzeigen) as TrShowExisting
    (zurückgewieseneÜbersetzungenAnzeigen) as TrShowRejected
    (anleitungHochladen) as TrUp
    tr -- TrShowMissing
    tr -- TrShowExisting
    tr -- TrShowRejected
    tr -- TrUp

    ' Sprachprüfer
    (freizugebendeAnleitungenAnzeigen) as spShow
    (anleitungFreigeben) as spFrei
    (anleitungZurückweisen) as spZurück
    sp -- spShow
    sp -- spFrei
    sp -- spZurück

    ' Fachprüfer
    (freizugebendeAnleitungenAnzeigen) as fpShow
    (anleitungFreigeben) as fpFrei
    (anleitungZurückweisen) as fpZurück
    fp -- fpShow
    fp -- fpFrei
    fp -- fpZurück
}

@enduml
