@startuml Aufgabe_2
'TODO: Anmerkung: Parameter werden in der Regel nicht angezeigt, da dies das Diagramm unübersichtlich macht!
hide empty description

'TODO: Statusreport ans System nötig um das Anzeigen zu ermöglichen!
'Anleitung Hochladen
[*] --> Hochgeladen : uploadAnleitung()
Hochgeladen --> Hochgeladen : uploadAnleitung()
SprachlichFreigegeben --> Hochgeladen : uploadAnleitung()
FachlichFreigegeben --> Hochgeladen : uploadAnleitung()
SprachlichZurückgewiesen --> Hochgeladen : uploadAnleitung()
FachlichZurückgewiesen --> Hochgeladen : uploadAnleitung()
Final --> Hochgeladen : uploadAnleitung() [Produkt.sperre = null]
FachlichUndSprachlichZurückgewiesen --> Hochgeladen : uploadAnleitung()

'Erste Freigabe/Zurückweisung
Hochgeladen --> SprachlichFreigegeben : setAnleitungFreigegeben() [Benutzer.rolle = Sprachprüfer & Benutzer != ersteller]
Hochgeladen --> FachlichFreigegeben : setAnleitungFreigegeben() [Benutzer.rolle = Fachprüfer & Benutzer != ersteller]
Hochgeladen --> SprachlichZurückgewiesen : setAnleitungZurückgewiesen() [Benutzer.rolle = Sprachprüfer]
Hochgeladen --> FachlichZurückgewiesen : setAnleitungZurückgewiesen() [Benutzer.rolle = Fachprüfer]

'Zweite Freigabe/Zurückweisung
SprachlichZurückgewiesen --> FachlichUndSprachlichZurückgewiesen : setAnleitungZurückgewiesen() [Benutzer.rolle = Fachprüfer]
FachlichZurückgewiesen --> FachlichUndSprachlichZurückgewiesen : setAnleitungZurückgewiesen() [Benutzer.rolle = Sprachprüfer]
SprachlichFreigegeben --> Final : setAnleitungFreigegeben() [Benutzer.rolle = Fachprüfer & Benutzer != ersteller]
FachlichFreigegeben --> Final : setAnleitungFreigegeben() [Benutzer.rolle = Sprachprüfer & Benutzer != ersteller]

'Anleitung Löschen
Hochgeladen --> [*] : deleteÜbersetzung()
SprachlichFreigegeben --> [*] : deleteÜbersetzung()
FachlichFreigegeben --> [*] : deleteÜbersetzung()
SprachlichZurückgewiesen --> [*] : deleteÜbersetzung()
FachlichZurückgewiesen --> [*] : deleteÜbersetzung()
Final --> [*] : deleteProdukt(), deleteÜbersetzung() [Produkt.sperre = null]
FachlichUndSprachlichZurückgewiesen --> [*] : deleteÜbersetzung()

Hochgeladen --> [*] : deleteProdukt() [Produkt.sperre = null]
SprachlichFreigegeben --> [*] : deleteProdukt() [Produkt.sperre = null]
FachlichFreigegeben --> [*] : deleteProdukt() [Produkt.sperre = null]
SprachlichZurückgewiesen --> [*] : deleteProdukt() [Produkt.sperre = null]
FachlichZurückgewiesen --> [*] : deleteProdukt() [Produkt.sperre = null]
FachlichUndSprachlichZurückgewiesen --> [*] : deleteProdukt() [Produkt.sperre = null]
@enduml