' TIME WASTED: 5h
@startuml

[*] --> Processing : anleitungHochladen(anleitung)
state Processing{
    state "Anleitung hochgeladen" as av
    [*] --> av
    state "sprachlich Freigegeben" as sprachFrei
    state "fachlich Freigegeben" as fachFrei
    state "sprachlich zurückgewiesen" as sprachZurück
    state "fachlich zurückgewisesn" as fachZurück
    state "fachlich und sprachlich zurückgewiesen" as fachSprachZurück
    state "fachlich zurückgewiesen,\nsprachlich freigegeben" as fachZurückSprachFrei
    state "fachlich freigegeben,\nsprachlich zurückgewiesen" as fachFreiSprachZurück
    state "final" as final
    
    av --> sprachFrei : anleitungFreigeben(anleitung, begründung{optional})\n[prüfer!=ersteller, rolle: Sprachprüfer]
    av --> fachFrei : anleitungFreigeben(anleitung, begründung{optional})\n[prüfer!=ersteller, rolle: Fachprüfer]

    sprachFrei --> fachZurückSprachFrei : anleitungZurückweisen(anleitung, begründung)\n[rolle: Fachprüfer]
    fachFrei --> fachFreiSprachZurück : anleitungZurückweisen(anleitung, begründung)\n[rolle: Sprachprüfer]

    sprachFrei --> final : anleitungFreigeben(anleitung, begründung{optional})\n[prüfer!=ersteller, rolle: Fachprüfer]
    fachFrei --> final : anleitungFreigeben(anleitung, begründung{optional})\n[prüfer!=ersteller, rolle: Sprachprüfer]

    av -> fachZurück : anleitungZurückweisen(anleitung, begründung{optional})\n[rolle: Fachprüfer]
    av -> sprachZurück : anleitungZurückweisen(anleitung, begründung{optional})\n[rolle: Sprachprüfer]
    sprachZurück --> fachSprachZurück : anleitungZurückweisen(anleitung, begründung)\n[rolle: Fachprüfer]
    fachZurück --> fachSprachZurück : anleitungZurückweisen(anleitung, begründung)\n[rolle: Sprachprüfer]
}
Processing <-- Processing : anleitungHochladen(anleitung)

Processing --> [*] : anleitungLöschen(anleitung)
Processing --> [*] : produktLöschen(produkt)

state "Anleitung gesperrt" as gesperrt

final --> gesperrt : produktSperren(produkt)
final <-- gesperrt : produktSperreAufheben(produkt)

@enduml